# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c23a0f9e211c55220dedb2389d37e4dc6e80a36e24d4e85bbcb2001115ebb580804b26d3f46d40173d2813c234f498c1c504a2fa2aeac11784a2d793f0d47f64

test:
  secret_key_base: 80eaf9193bce8d8f32d1916df373b298a17edc627273790e8971bcfa02dc991f7b11c3e634b5fccc10328c84dba8e8d3e81e3264dc9d8e6bc97344365afd1556

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
